// Generated by https://quicktype.io

export interface DahsboardSummaryResponse {
  numberOfOrders:          number;
  paidOrders:              number;
  notPaidOrders:           number;
  numberOfClients:         number;
  numberOfProducts:        number;
  productsWithNoInventory: number;
  lowInventory:            number;
}
